#!/usr/bin/env python
#
# $Id$

import os

Import('env')
Import('sourceFiles')
Import('library')

env = env.Clone()
env.Append(CPPPATH = '../')

# build a object file form each source file
for file in sourceFiles:
	basename = os.path.basename(file.name)
	name = os.path.splitext(basename)
	
	if env['ARCHITECTURE'] == 'pc':
		program = env.Program(name[0], file.name, LIBS=['robot','boost_thread'], LIBPATH=['../build/','/usr/lib/'])
	else:
		program = env.Program(name[0], file.name, LIBS=['robot'], LIBPATH=['../build/'])
	env.Default(program)
	
	if env['ARCHITECTURE'] == 'avr':
		env.Default(env.Hex(program))
		env.Default(env.Listing(program))
