#!/usr/bin/env python
#
# $Id$

import os

Import('env')
Import('sourceFiles')
Import('library')

env = env.Clone()
env.Append(CPPPATH = '../src')

# build a object file form each source file
for file in sourceFiles:
	defines = env.get('CPPDEFINES', {})
	defines.update(file.defines)
	defines['BASENAME'] = file.basename
	
	program = env.Program(file.basename, file.name,
							CPPDEFINES=defines,
							LIBS=env['LIBS'] + ['robot'],
							LIBPATH=env['LIBPATH'] + ['../build/'])
	env.Default(program)
	
	if env['ARCHITECTURE'] == 'avr':
		env.Default(env.Hex(program))
		env.Default(env.Listing(program))
