
Import('env')
Import('options')

if env['ARCHITECTURE'] == 'pc':
	SOURCE = """
		logger/logger.cpp
		logger/console_output_writer.cpp
		logger/abstract_output_writer.cpp
		logger/logger_message_forwarder.cpp
	"""
else:
	SOURCE = """
	
	"""

objects = []
for file in Split(SOURCE):
	objects.append(env.Object(file))

Return('objects')
