run:
	python3 run_all.py

run-avr:
	python3 run_all.py at

run-stm32:
	python3 run_all.py stm32f0
	python3 run_all.py stm32f1
	python3 run_all.py stm32f2
	python3 run_all.py stm32f3
	python3 run_all.py stm32f4
	python3 run_all.py stm32f7
	python3 run_all.py stm32l4

run-failed:
	python3 run_all.py failed
