# Copyright (c) 2018, Niklas Hauser
#
# This file is part of the modm project.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

run-quick:
	python3 run_all.py at sam stm32 --quick

run-avr:
	python3 run_all.py at

run-sam:
	python3 run_all.py sam

run-stm32:
	python3 run_all.py stm32

run-failed:
	python3 run_all.py failed
