
# path to the xpcc root directory
rootpath = '../../../..'

env = Environment(tools = ['xpcc'], toolpath = [rootpath + '/scons/site_tools'])

# find all source files
files = env.FindFiles('.')

# build the program
program = env.Program(target = env['XPCC_CONFIG']['general']['name'], source = files.sources)

env['CXXFLAGS'].append("-g")

# build the xpcc library
env.XpccLibrary()

# create a file called 'defines.hpp' with all preprocessor defines if necessary
env.Defines()

env.Alias('size', env.Size(program))
env.Alias('symbols', env.Symbols(program))
env.Alias('defines', env.ShowDefines())

hexfile = env.Hex(program)
binfile = env.Bin(program)

# env.Alias('program', env.OpenOcd(program))
env.Alias('init', env.LpcLinkInit(program))
env.Alias('program', env.LpcLinkFlash(binfile))
env.Alias('debug', env.GdbDebug(program))
env.Alias('lpcdebug', env.LpcLinkDebug(program))
env.Alias('build', [hexfile, binfile, env.Listing(program)])
env.Alias('all', ['build', 'size'])

env.Default('all')
