# path to the xpcc root directory
xpccpath = '../../..'
# execute the common SConstruct file
exec(compile(open(xpccpath + '/scons/SConstruct', "rb").read(), xpccpath + '/scons/SConstruct', 'exec'))

# change compile flags to debug
#env['CXXFLAGS'].remove("-Os")
env['CXXFLAGS'].append("-O0")
env['CXXFLAGS'].append("-g")
