# path to the xpcc root directory
xpccpath = '../../..'
# execute the common SConstruct file
execfile(xpccpath + '/scons/SConstruct')

# change compile flags to debug
#env['CXXFLAGS'].remove("-Os")
env['CXXFLAGS'].append("-O0")
env['CXXFLAGS'].append("-g")
