# path to the xpcc root directory
xpccpath = '../../..'
# execute the common SConstruct file
exec(compile(open(xpccpath + '/scons/SConstruct', "rb").read(), xpccpath + '/scons/SConstruct', 'exec'))

# build xpcc_build_info.hpp file
env.BuildInfoHeader()