#!/usr/bin/env python
#
# $Id: SConscript 88 2009-10-16 23:07:26Z dergraaf $

Import('env')
Import('sourceFiles')

env = env.Clone()
env.Append(CPPPATH = '.')

# build a object file form each source file
objects = []
for file in sourceFiles:
	defines = env.get('CPPDEFINES', {})
	defines.update(file.defines)
	defines['BASENAME'] = file.basename
	
	object = env.Object(file.name, CPPDEFINES=defines)
	objects.append(object)

# link them all together to create the library
library = env.Library(target='robot', source=objects)

#env.Default(library)
#env.Alias('lib', library)

Return('library')
