#!/usr/bin/env python
#
# $Id$

Import('env')
Import('sourceFiles')

# build a object file form each source file
objects = []
for file in sourceFiles:
	defines = env.get('CPPDEFINES', {})
	defines.update(file.defines)
	
	object = env.Object(file.name, CPPDEFINES=defines)
	objects.append(object)

# link them all together to create the library
library = env.Library(target='robot', source=objects)

env.Default(library)
env.Alias('lib', library)

Return('library')
