#!/usr/bin/env python
#
# $Id: SConscript 88 2009-10-16 23:07:26Z dergraaf $

Import('env')
Import('sources')

env = env.Clone()
env.Append(CPPPATH = '.')

# build a object file form each source file
objects = []
for file in sources:
	defines = env.get('CPPDEFINES', {})
	defines.update(file.defines)
	defines['BASENAME'] = file.basename
	
	object = env.Object(file.name, CPPDEFINES=defines)
	objects.append(object)

# link them all together to create the library
library = env.Library(target='robot', source=objects)

Return('library')
