#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Copyright (c) 2010-2012, Fabian Greif
# Copyright (c) 2011, Georgi Grinshpun
# Copyright (c) 2012, Sascha Schade
# Copyright (c) 2014, Daniel Krebs
# Copyright (c) 2016, Niklas Hauser
#
# This file is part of the modm project.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
# -----------------------------------------------------------------------------

# path to the xpcc root directory
xpccpath = '../../../..'
# execute the xpcc basic
execfile(xpccpath + '/scons/SConstruct')
