name: Run hosted tests on Windows

on: [pull_request]

jobs:
  windows_hosted:
    runs-on: windows-2019
    env:
      PYTHONIOENCODING: "utf-8"

    steps:

      # Disabling snake-oil for performance reasons
      - name: Disable Windows Defender
        run: Set-MpPreference -DisableRealtimeMonitoring $true

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install Python packages
        run: |
          pip install --user modm scons future

      - name: Download GCC for Windows
        run: |
          $ProgressPreference = 'SilentlyContinue'
          Invoke-WebRequest -OutFile winlibs-gcc.zip https://github.com/brechtsanders/winlibs_mingw/releases/download/10.2.0-11.0.0-8.0.0-r5/winlibs-x86_64-posix-seh-gcc-10.2.0-mingw-w64-8.0.0-r5.zip

      - name: Unpack GCC for Windows
        shell: powershell
        run: |
          Add-Type -Assembly "System.IO.Compression.Filesystem"
          [System.IO.Compression.ZipFile]::ExtractToDirectory("winlibs-gcc.zip", "C:\winlibs-gcc")
          dir C:\winlibs-gcc
          dir C:\winlibs-gcc\mingw64
          echo "C:\winlibs-gcc\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Show lbuild and gcc version
        run: |
          lbuild --version
          gcc --version
          g++ --version
          make --version
          python -c "import os; print(os.cpu_count())"

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Git Submodules
        shell: bash
        run: |
          git submodule update --init

      - name: Hosted Examples
        shell: bash
        run: |
          (cd examples && python ../tools/scripts/examples_compile.py linux/assert linux/block_device linux/build_info linux/git linux/logger linux/printf)

      - name: Hosted Unittests
        shell: bash
        run: |
          (cd test && make run-hosted-windows)
